
name: build-luajit

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: checkout
        uses: actions/checkout@v4          

      - name: build
        id: build
        shell: cmd
        run: call build.cmd

  release:
    runs-on: ubuntu-24.04
    needs: build
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: release
        run: |
            echo '[LuaJIT commit](https://github.com/LuaJIT/LuaJIT/commit/${{ steps.build.outputs.LuaJIT_COMMIT }})'

      - name: get artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: LuaJIT-${{ needs.build.outputs.OUTPUT_DATE }}
          merge-multiple: true

      - name: upload artifacts
        run: gh release upload '${{ needs.build.outputs.OUTPUT_DATE }}' LuaJIT-${{ needs.build.outputs.OUTPUT_DATE }}.zip -R "${GITHUB_REPOSITORY}"
